name: Create Archive
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r Monokakido.popclipextz Monokakido.popclipext
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Monokakido.popclipextz"
        token: ${{ secrets.GITHUB_TOKEN }}
